wandb_config:
    project_name: "v3-RATE-TMaze" #"CA-RATE_TMaze"
    wwandb: True
    wcomet: False

data_config:
  # noise augmentation of data
  multiplier: 1000 # 1000
  # number of hint steps
  hint_steps: 1
  # cutting previous data in half when adding new segment during training. 
  cut_dataset: False
  # reward on succesful completion of an episode
  desired_reward: 1.0 # defalt: 1.0
  # adding only succesful trajectories to the dataset
  win_only: True # default: True

training_config:
  learning_rate: 0.0003 # 1e-4
  lr_end_factor: 0.1
  beta_1: 0.9
  beta_2: 0.95
  weight_decay: 0.1
  batch_size: 64 # 64
  warmup_steps: 100  # 100
  grad_norm_clip: 1.0 # 1.0
  epochs: 50 # 50
  ckpt_epoch: 10
  use_erl_stop: False
  coef: 0.0
  # inference during training
  online_inference: True
  last_inference: True
  # ! WARNING ! IMPORTANT INFO
  # * IF YOU WANT TO TRAIN DT WITH context_length=90 (or if you want to train RATE with
  # * 3 segments and context 30), set context_length=30 and sections=3
  context_length: 30 # if RATE/GRATE: L = L, if DT: L = sections * L
  sections: 3        # if RATE/GRATE: S = S, if DT: S = 1
  

model_config:
  mode: "tmaze"
  STATE_DIM: 4
  ACTION_DIM: 1
  n_token: 10000 # vocab_size
  n_layer: 8 # 8 
  n_head: 10 # 10
  n_head_ca: 4 # 4
  d_model: 64 # 64
  d_head: 64 # 64
  d_inner: 64 # 64
  dropout: 0.05 # 0.05
  dropatt: 0.0 # 0.0
  mem_len: 0 # 0
  ext_len: 0 # 0
  tie_weight: False
  num_mem_tokens: 5 # 5 d_head * nmt = diff params
  mem_at_end: True
  mrv_act: 'relu'
  skip_dec_ffn: True

online_inference_config:
  episode_timeout: 
  corridor_length: 





