wandb_config:
    project_name: "v3-RATE_AAR"
    wwandb: False
    wcomet: True

data_config:
  # noise augmentation of data
  multiplier: 1000
  # cutting previous data in half when adding new segment during training. 
  cut_dataset: False


training_config:
  learning_rate: 0.0003 # 1e-4
  lr_end_factor: 0.1
  beta_1: 0.9
  beta_2: 0.95
  weight_decay: 0.1
  batch_size: 64 # 64
  warmup_steps: 100  # 100
  grad_norm_clip: 1.0 # 0.25 
  epochs: 75 # 50
  ckpt_epoch: 2
  use_erl_stop: False
  # inference during training
  online_inference: False
  # adding weight to the loss on the last valid action
  coef: 0.0
  # ! WARNING ! IMPORTANT INFO
  # * IF YOU WANT TO TRAIN DT WITH context_length=90 (or if you want to train RATE with
  # * 3 segments and context 30), set context_length=30 and sections=3
  context_length: 30 # if RATE/GRATE: L = L, if DT: L = sections * L
  sections: 3        # if RATE/GRATE: S = S, if DT: S = 1

model_config:
  mode: "aar"
  STATE_DIM: 3
  ACTION_DIM: 1

  n_token: 10000 # vocab_size
  n_layer: 6 # 8 
  n_head: 8 # 10
  n_head_ca: 4 # ! number of MRV heads
  d_model: 64 # 256
  d_head: 64 # 128 # divider of d_model
  d_inner: 64 # 512 # > d_model
  dropout: 0.05 # 0.1  
  dropatt: 0.0 # 0.05
  mem_len: 0
  ext_len: 0
  tie_weight: False
  num_mem_tokens: 5 # 5 d_head * nmt = diff params
  mem_at_end: True
  mrv_act: 'relu'
  skip_dec_ffn: True

online_inference_config:
  stay_number: 





