program: recurrent_baselines/obs_only_LSTM_GRU/vizdoom/lstm_train_vizdoom.py
method: bayes
metric:
  name: ReturnsMean_56.5
  goal: maximize
parameters:
  model_config.num_layers:
    values: [1, 2]
  model_config.hidden_size:
    values: [64, 128]
  model_config.dropout:
    values: [0, 0.2]

early_terminate:
  type: hyperband 
  min_iter: 3

# python recurrent_baselines/obs_only_LSTM_GRU/vizdoom/run_sweep_lstm.py

# command:
#   - ${env}
#   - ${interpreter}
#   - ${program}
#   - --model_mode=LSTM
#   - --curr=false
#   - --ckpt_folder=sweep_lstm
#   - --max_n_final=3
#   - --text=sweep_lstm