program: recurrent_baselines/Mamba/tmaze/mamba_train_tmaze.py
method: bayes
metric:
  name: Success_rate
  goal: maximize
parameters:
  model_config.n_layer:
    values: [1, 2, 3, 4]
  model_config.d_model:
    values: [32, 64, 128, 256, 512]

early_terminate:
  type: hyperband 
  min_iter: 3

# python recurrent_baselines/Mamba/tmaze/sweeps_K_30/run_sweep_mamba.py

# command:
#   - ${env}
#   - ${interpreter}
#   - ${program}
#   - --model_mode=LSTM
#   - --curr=false
#   - --ckpt_folder=sweep_lstm
#   - --max_n_final=3
#   - --text=sweep_lstm